// This is college Project/worknest/frontend/src/app/auth/login/login.component.ts
import { Component, EventEmitter, Output } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { Router } from '@angular/router'
import { AuthService } from '../../services/auth.service'

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {

  @Output() switchToRegister = new EventEmitter<void>()

  email = ''
  password = ''

  loading = false
  errorMessage = ''

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  login() {
    this.loading = true
    this.errorMessage = ''

    this.authService.login({
      email: this.email,
      password: this.password
    }).subscribe({
      next: () => {
        // ✅ token AuthService me save ho chuka hai
        // ✅ direct dashboard redirect
        this.router.navigate(['/dashboard'])
      },
      error: (err: any) => {
        this.loading = false
        this.errorMessage =
          err?.error?.message || 'Login failed'
      },
      complete: () => {
        this.loading = false
      }
    })
  }

  onSwitch() {
    this.switchToRegister.emit()
  }
}

<!-- AUTH PAGE -->
<div class="auth-page">

  <!-- AUTH CARD -->
  <div class="auth-card">

    <!-- HEADER -->
    <div class="auth-header">
      <h2 class="auth-title">Welcome Back</h2>
      <p class="auth-subtitle">
        Login to continue to your account
      </p>
    </div>

    <!-- FORM -->
    <form class="auth-form" (ngSubmit)="login()">

      <!-- EMAIL -->
      <div class="form-group">
        <label for="email">Email address</label>
        <input
          id="email"
          type="email"
          name="email"
          [(ngModel)]="email"
          placeholder="you@example.com"
          required
        />
      </div>

      <!-- PASSWORD -->
      <div class="form-group">
        <label for="password">Password</label>
        <input
          id="password"
          type="password"
          name="password"
          [(ngModel)]="password"
          placeholder="••••••••"
          required
        />
      </div>

      <!-- BUTTON -->
      <button
        type="submit"
        class="btn-primary"
        [disabled]="loading"
      >
        {{ loading ? 'Logging in…' : 'Login' }}
      </button>

    </form>

    <!-- FEEDBACK -->
    <div class="auth-feedback">
      <p class="error-message" *ngIf="errorMessage">
        {{ errorMessage }}
      </p>
    </div>

    <!-- FOOTER -->
    <div class="auth-footer">
      <span>New user?</span>
      <a href="#" (click)="onSwitch(); $event.preventDefault()">
        Create account
      </a>
    </div>

  </div>
</div>

// worknest/React Frontend/worknest-frontend/src/pages/Login.jsx
import { useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { loginApi } from "../services/authApi";
import { saveAuth, getToken } from "../utils/auth";
import "./Login.css";

function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const navigate = useNavigate();

  if (getToken()) {
    return <Navigate to="/dashboard" replace />;
  }

  const handleLogin = async (e) => {
    e.preventDefault();

    try {
      const res = await loginApi({ email, password });
      saveAuth(res.data.accessToken, res.data.user);
      navigate("/dashboard");
    } catch (err) {
      alert("Login failed");
      console.error(err);
    }
  };

  return (
    <div className="auth-page">
      <div className="auth-card">
        <h2 className="auth-title">Welcome Back</h2>
        <p className="auth-subtitle">Sign in to your account</p>

        <form className="auth-form" onSubmit={handleLogin}>
          <div className="form-group">
            <label>Email</label>
            <input
              type="email"
              placeholder="Enter your email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>

          <div className="form-group">
            <label>Password</label>
            <input
              type="password"
              placeholder="Enter your password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>

          <button className="btn-primary" type="submit">
            Login
          </button>
        </form>
      </div>
    </div>
  );
}

export default Login;
