// worknest/frontend/src/app/auth/login/login.component.ts
import { Component, EventEmitter, Output } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { HttpClient } from '@angular/common/http'

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {

  // 🔁 switch signal to parent
  @Output() switchToRegister = new EventEmitter<void>()

  email: string = ''
  password: string = ''

  loading: boolean = false
  successMessage: string = ''
  errorMessage: string = ''

  constructor(private http: HttpClient) {}

  login() {
    this.loading = true
    this.successMessage = ''
    this.errorMessage = ''

    this.http.post<any>('http://localhost:3000/auth/login', {
      email: this.email,
      password: this.password
    }).subscribe({
      next: (res) => {
        this.successMessage = 'Login successful ✅'
        this.loading = false
        localStorage.setItem('token', res.data.token)
      },
      error: (err) => {
        this.errorMessage =
          err?.error?.message || 'Login failed'
        this.loading = false
      }
    })
  }

  // 🔁 manual switch (link click)
  
onSwitch() {
  console.log('📤 emitting switchToRegister')
  this.switchToRegister.emit()
}

}

<div class="auth-page">
  <div class="auth-card">

    <!-- Title -->
    <h2 class="auth-title">Welcome Back</h2>
    <p class="auth-subtitle">
      Login to continue to your account
    </p>

    <!-- Login Form -->
    <form class="auth-form" (ngSubmit)="login()">

      <!-- Email -->
      <div class="form-group">
        <label>Email</label>
        <input
          type="email"
          name="email"
          [(ngModel)]="email"
          placeholder="Enter your email"
          required
        />
      </div>

      <!-- Password -->
      <div class="form-group">
        <label>Password</label>
        <input
          type="password"
          name="password"
          [(ngModel)]="password"
          placeholder="Enter your password"
          required
        />
      </div>

      <!-- Button -->
      <button
        type="submit"
        class="btn-primary"
        [disabled]="loading"
      >
        {{ loading ? 'Logging in...' : 'Login' }}
      </button>

    </form>

    <!-- SWITCH LINK 🔁 -->
    <p style="margin-top:16px; text-align:center">
      New user?
      <a href="#" (click)="onSwitch(); $event.preventDefault()">
  Create account
</a>

    </p>

    <!-- Success Message -->
    <p class="success-message" *ngIf="successMessage">
      {{ successMessage }}
    </p>

    <!-- Error Message -->
    <p class="error-message" *ngIf="errorMessage">

// worknest/React Frontend/worknest-frontend/src/pages/Login.jsx
import { useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { loginApi } from "../services/authApi";
import { saveAuth, getToken } from "../utils/auth";
import "./Login.css";

function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const navigate = useNavigate();

  if (getToken()) {
    return <Navigate to="/dashboard" replace />;
  }

  const handleLogin = async (e) => {
    e.preventDefault();

    try {
      const res = await loginApi({ email, password });
      saveAuth(res.data.accessToken, res.data.user);
      navigate("/dashboard");
    } catch (err) {
      alert("Login failed");
      console.error(err);
    }
  };

  return (
    <div className="auth-page">
      <div className="auth-card">
        <h2 className="auth-title">Welcome Back</h2>
        <p className="auth-subtitle">Sign in to your account</p>

        <form className="auth-form" onSubmit={handleLogin}>
          <div className="form-group">
            <label>Email</label>
            <input
              type="email"
              placeholder="Enter your email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>

          <div className="form-group">
            <label>Password</label>
            <input
              type="password"
              placeholder="Enter your password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>

          <button className="btn-primary" type="submit">
            Login
          </button>
        </form>
      </div>
    </div>
  );
}

export default Login;
